### ISSUE TITLE
rar and or zip files unavailable

### ISSUE THREAD

**Issue by IOPNR** [Quantrik/Kyuu#1]
Hello, first and foremost - Thank you for releasing your designs to the community for personal use. Your design is iconic and I'm pretty stoked to be able to build my very own and I'm sure many others in the community are as well.

I'm writing with regard to uploading the pcb files for printing - I am unable to find a rar and or zip file within the pcb branch of your repository. Am I missing something? I had to do a workaround for the case files as well but managed to figure it out. Any help would be greatly appreciated.

All best to you and yours!

**Comment by ctrltri** [comment]
You need to clone the repository and all the files will be there.

**Comment by Quantrik** [comment]
You can look at the `gerbers` directory. They contain the output files that should be added to a `zip` or `tar` package.
