### ISSUE TITLE
WK Version

### ISSUE THREAD

**Issue by adnn-alc** [Quantrik/Kyuu#3]
Hello! Is it possible to have file for the WK version as well instead of only WKL?

I'm not really a fan of WKL layout but would like to try and get Kyuu made for myself. Thank you.

**Comment by ratchet303** [comment]
A little late, but I was looking into building a WK Kyuu. Here is a .step file I made for a WK Kyuu, and it seems the plate and PCB designs already have the windows key, there was just a blocker for the WKL version (someone correct me if I'm wrong). 
[https://drive.google.com/file/d/1QS4Nr9sc4B6cRykTrNMsWIS5eKDg6lz1/view?usp=sharing](url)
